# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    webp:
        generate: true
    default_filter_set_settings:
        format: webp

    filter_sets:
        partners:
            filters:
                relative_resize:
                    heighten: 70

        logo_bg_color:
            filters:
                background:
                    color: "#fe7600"
                    position: center
                relative_resize:
                    widen: 400

        logo_header:
            filters:
                relative_resize:
                    widen: 624

        event386:
            quality: 75
            filters:
                relative_resize:
                    widen: 386

        featurette:
            quality: 75
            filters:
                thumbnail:
                    size: [500, 500]
                    mode: outbound

        favicon:
            filters:
                thumbnail:
                    size: [32, 32]
                    mode: outbound
